### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by tjheeta** [mnussbaumer/cssex#8]
Hey, we were chatting to the forum earlier. I was trying out the library and found that for some reason this doesn't render. I know it's super-early in dev cycle, but figured might as well file it in case you don't know about it. 

This doesn't work.
```
@media only screen {
   header nav a {
       display: block;
       color: white;
       text-decoration: none;

       a:focus, a:hover {
         color: #000;
       };
   }
}
```

I believe it has to do with the some multiple nesting. 

This works.
```
   header nav a {
       display: block;
       color: white;
       text-decoration: none;
   }

       a:focus, a:hover {
         color: #002;
       };
@media only screen {
  div { color: green; }
}
```

This works.
```
@media only screen {
   header nav a {
       display: block;
       color: white;
       text-decoration: none;
   }

       a:focus, a:hover {
         color: #002;
       };
  div { color: blue; }
}
```

However, removing the last div with color blue causes it to not correctly update.

**Comment by mnussbaumer** [comment]
Hey, thanks for giving it a try! 

Yeap, the issue is that it's crashing due to the trailing ";" on:
```
a:focus, a:hover {
     color: #000;
};
```

Although interesting that it doesn't on the last one though.

I'll be pushing changes up today, including a fix on this, and additional tests.

**Comment by mnussbaumer** [comment]
@tjheeta I was thinking, my inclination is to (eventually) make all invalid things crash, for instance this would show you an error with line/col. I think this approach is the correct specially because it's a preprocessor, you can fix this while you'r working, and it's better than trying to "auto-fix"/ignore the issue. Do you have any thoughts on that?

**Comment by tjheeta** [comment]
Postel's law comes to mind. 

Syntactical correctness is great for new projects and I think could be helpful. I think older projects might have an issue with a strict mode though. 

From a user perspective, 80% will already have something working.  They will try the library, but if it doesn't compile the stylesheet they will need to do hours of work before seeing a result. Will they bother? After they see a result, then they'll decide whether they like the tool or not and make a decision to migrate. 

So, my opinion is that a strict mode is good as an option, but not as the default. Throwing warnings is fine, people generally get around to fixing them to see a nice compile screen.

**Comment by mnussbaumer** [comment]
The idea of making "ignorable" errors be warnings and having a toggle for strictness sounds good. 
I will add it to the roadmap.

**Comment by mnussbaumer** [comment]
I think in the end I'm not going to allow this. It could be helpful when the errors are things that a browser can ignore, the issue is that other errors if dropped silently can make it quite hard to understand. I think that given the use case of being a pre processor that you have running as you're developing it makes more sense to just fail. If I have a syntax error I prefer to have it shown to me - specially because functions, variables and eex blocks all re-insert code that is parsed after they return. I might revisit this after finishing everything for v1 but as of now I'm going to keep errors.

**Comment by mnussbaumer** [comment]
Due to https://github.com/mnussbaumer/cssex/issues/49 this won't happen anymore with multiple, or misplaced semicolons, as was the case with the original report - In this particular case I would actually still want it to crash, but writing the parser in a way that errors out in this particular case while just dropping semicolons following other semicolons (the issue #49 addressed) is probably more work than warranted, so it will just drop misplaced semicolons always
